name: hoster
description: "A Hosting platform."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  flutter_animate: ^4.5.0
  icons_plus: ^5.0.0
  toastification: ^1.2.1
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  flutter_animated_button: ^2.0.3
  video_player: ^2.8.5
  animated_loading_border: ^0.0.2
  date_format: ^2.0.7
  animated_toggle_switch: ^0.8.2
  data_table_2: ^2.5.12
  fl_chart: ^0.67.0
  pie_chart: ^5.4.0
  http: ^1.2.1
  path_provider: ^2.1.3
  animated_custom_dropdown: ^3.0.0
  google_generative_ai: ^0.4.0
  uuid: ^4.4.0
  animated_text_kit: ^4.2.2
  flutter_animated_loadingkit: ^0.0.7
  emailjs: ^1.3.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
    - assets/videos/
